[lldb][test][win][x86_64] UTF8 encode LLDB output before printing
When output is printed to the console in Windows cmd.exe the output
is converted to Code Page 1252 and some utf-8 characters translate
to <undefined> resulting in a test failure message like:

```
======================================================================
ERROR: test_dwarf (TestChar1632T.Char1632TestCase.test_dwarf)
   Test that the C++11 support for char16_t and char32_t works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 1761, in test_method
    return attrvalue(self)
           ^^^^^^^^^^^^^^^
  File "C:\workspace\llvm-project\lldb\test\API\lang\cpp\char1632_t\TestChar1632T.py", line 52, in test
    self.expect(
  File "C:\workspace\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 2362, in expect
    self.runCmd(
  File "C:\workspace\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 986, in runCmd
    print("output:", self.res.GetOutput())
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 59-61: character maps to <undefined>
Config=x86_64-C:\workspace\llvm-project\build\bin\clang.exe
----------------------------------------------------------------------
```

This causes each of these tests to be `UNRESOLVED`:

- lldb-api :: lang/cpp/char1632_t/TestChar1632T.py
- lldb-api :: lang/cpp/char8_t/TestCxxChar8_t.py
- lldb-api :: lang/cpp/wchar_t/TestCxxWCharT.py