[lldb][test][x86_64] Disable failing TestNestedExpressions test case
This test fails with an assertion error:

  error: Couldn't look up symbols:  A::B::C::enum_static
  Hint: The expression tried to call a function that is not present in the target, perhaps because it was optimized out by the compiler.

Tests are not currently run on Windows x86_64 in CI.